<div>
<link
      rel="stylesheet"
      href="{{asset('theme/plugins/datatables-bs4/css/dataTables.bootstrap4.min.css')}}"
    />
    <link
      rel="stylesheet"
      href="{{asset('theme/plugins/datatables-responsive/css/responsive.bootstrap4.min.css')}}"
    />
    <link
      rel="stylesheet"
      href="{{asset('theme/plugins/datatables-buttons/css/buttons.bootstrap4.min.css')}}"
    />
</div>